# Dubai Real Estate 2025 - Dataset Creation and Initial Filtering
This notebook constructs the baseline 2025 residential transactions dataset from the original Dubai Data & Statistics Establishment (DDSE) data source.
The objective is to extract, filter, and store a manageable, analysis-ready subset focused on Dubai’s residential property market.

## Main Steps
**- Column Reduction:** Redundant, administrative, and irrelevant fields are dropped to streamline subsequent analysis.

**- Data Loading:** The full raw dataset is too large to comfortably load and process as a single DataFrame. It is therefore read in chunks to handle memory constraints efficiently.

**- Year Filtering:** Only records corresponding to the year 2025 are retained.

**- Deduplication:** Verified that all transactions have unique transaction IDs.

**- Property-Type Filtering:** Non-residential entries are excluded; the dataset is restricted to Units and Villas.

**- Preliminary Assessment:** Value distributions, feature completeness and data types are reviewed to guide cleaning strategy.

**- Export:** The resulting filtered subset is saved as transactions_2025.csv, forming the input for subsequent preprocessing stages.

## Outcome:
The exported dataset provides a reliable, size-reduced and structurally coherent foundation for detailed cleaning, ensuring the next stage begins with only relevant residential records.

# Libraries

In [3]:
import pandas as pd # For Data Manipulation

# Data

In [6]:
# Path to the original CSV
file_path = "Transactions.csv"

# 1. Column Reduction
Several columns contain the same information in english, arabic and encoded (e.g. 'property_type'). The project will be performed in english, so the arabic versions are removed to reduce file size. For future predictive models, the variables will be encoded again, but for the initial analysis the english version is kept to allow a better understanding of each feature, hence the encoded features are also initially dropped.

Since this is a transactions database, around 99% of the entries contain no information about renting. The two features associated with rent are therefore also removed.

'procedure_name' is removed for escaping the scope of this project. 'Property subtype' is removed since all values are either the respective 'property type' or null.

'building_name', 'project name' and 'master_project' are currently kept: they will be used to extract developer's information.

In [9]:
# List of columns to remove
columns_to_remove = [
    'procedure_id', 'trans_group_id', 'trans_group_ar',
    'procedure_name_ar', 'property_type_id', 'property_type_ar',
    'property_sub_type_id', 'property_sub_type_en','property_sub_type_ar',
    'property_usage_ar', 'reg_type_id', 'reg_type_ar', 'area_id', 'area_name_ar',
    'building_name_ar', 'project_number', 'project_name_ar',
    'master_project_ar', 'nearest_landmark_ar', 'nearest_metro_ar',
    'nearest_mall_ar', 'rooms_ar',  'procedure_name_en',
    'rent_value', 'meter_rent_price'
]

# 2. Data Loading
The original file contains over 1.2M entries and 42 rows. The aim is to reduce the dataset to a more manageable size, by loading it in chunks and instantly removing all unnecessary columns.

For the initial analysis, only data from 2025 is kept, which still contains over 250k entries, enough for a thorough analysis. For future project expansions (i.e. Time Analysis), entries from previous years will also be included.

In [12]:
chunk_size = 100_000

chunks_list = []  # list to store filtered chunks
new_rows = 0

for chunk in pd.read_csv(file_path, chunksize=chunk_size, low_memory=False):
    # Drop unwanted columns
    chunk_reduced = chunk.drop(columns=columns_to_remove, errors='ignore')
    
    # Convert 'instance_date' to datetime
    chunk_reduced['instance_date'] = pd.to_datetime(chunk_reduced['instance_date'], dayfirst=True, errors='coerce')
    
    # Keep only transactions from 2025
    chunk_filtered = chunk_reduced[chunk_reduced['instance_date'].dt.year == 2025]
    
    # Update total row count
    new_rows += len(chunk_filtered)
    
    # Append filtered chunk to list
    chunks_list.append(chunk_filtered)

# Concatenate all chunks into a single DataFrame
df_filtered = pd.concat(chunks_list, ignore_index=True)

print(f"Total rows in final DataFrame: {len(df_filtered)}")

Total rows in final DataFrame: 267517

In [14]:
# Creating a copy to ensure no alteration on the original data
df = df_filtered.copy()

In [16]:
df.head(2)

,transaction_id,trans_group_en,instance_date,property_type_en,property_usage_en,reg_type_en,area_name_en,building_name_en,project_name_en,master_project_en,...,nearest_metro_en,nearest_mall_en,rooms_en,has_parking,procedure_area,actual_worth,meter_sale_price,no_of_parties_role_1,no_of_parties_role_2,no_of_parties_role_3
0,1-11-2025-22014,Sales,2025-05-29,Building,Residential / Commercial,Existing Properties,Al Hamriya,NaN,NaN,NaN,...,Burjuman Metro Station,Dubai Mall,NaN,0,5171.22,73500000.0,14213.28,1.0,1.0,0.0
1,3-9-2025-3468,Gifts,2025-06-12,Building,Residential,Existing Properties,Al Satwa,NaN,NaN,NaN,...,Trade Centre Metro Station,Dubai Mall,NaN,0,105.29,2000001.0,18995.17,1.0,2.0,0.0

# 3. Deduplication
Verify that all transaction IDs are unique.

In [20]:
# Checking for any duplicated entries
df['transaction_id'].duplicated().sum()

0

# 4. Property Type Filtering
For this project, the analysis is restricted to residential transactions involving Units and Villas. Land, Buildings and other property types are excluded because the project focuses on residential property price formation at the individual property level.

In [23]:
df['property_usage_en'].value_counts(dropna=False)

property_usage_en
Residential                              230881
Commercial                                20876
Other                                      8246
Hospitality                                4212
Industrial                                 1902
Residential / Commercial                    859
Multi-Use                                   447
Agricultural                                 40
Industrial / Commercial                      38
Storage                                      12
Industrial / Commercial / Residential         4
Name: count, dtype: int64

In [25]:
df['property_type_en'].value_counts(dropna=False)

property_type_en
Unit        208189
Land         29648
Villa        28175
Building      1505
Name: count, dtype: int64

In [27]:
# Keeping only residential properties
df = df[df['property_usage_en']=='Residential']

# Keep only Units and Villas
df = df[df['property_type_en'].isin(['Unit', 'Villa'])].copy()

In [29]:
# Dropping the column since it provides no more value
df = df.drop('property_usage_en', axis =1)

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 223801 entries, 2 to 267516
Data columns (total 20 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   transaction_id        223801 non-null  object
 1   trans_group_en        223801 non-null  object
 2   instance_date         223801 non-null  datetime64[ns]
 3   property_type_en      223801 non-null  object
 4   reg_type_en           223801 non-null  object
 5   area_name_en          223801 non-null  object
 6   building_name_en      195908 non-null  object
 7   project_name_en       199544 non-null  object
 8   master_project_en     195816 non-null  object
 9   nearest_landmark_en   161164 non-null  object
 10  nearest_metro_en      131330 non-null  object
 11  nearest_mall_en       128649 non-null  object
 12  rooms_en              216627 non-null  object
 13  has_parking           223801 non-null  int64
 14  procedure_area        223801 non-null  float64
 15  actual_worth          223801 non-null  float64
 16  meter_sale_price      223801 non-null  float64
 17  no_of_parties_role_1  223764 non-null  float64
 18  no_of_parties_role_2  223764 non-null  float64
 19  no_of_parties_role_3  223764 non-null  float64
dtypes: datetime64[ns](1), float64(6), int64(1), object(12)
memory usage: 35.9+ MB

In [33]:
df['property_type_en'].value_counts()

property_type_en
Unit     195908
Villa     27893
Name: count, dtype: int64

# 5. Preliminary Assessment
Quick check of what type of information and how many null values each column has.

In [36]:
df.columns

Index(['transaction_id', 'trans_group_en', 'instance_date', 'property_type_en',
       'reg_type_en', 'area_name_en', 'building_name_en', 'project_name_en',
       'master_project_en', 'nearest_landmark_en', 'nearest_metro_en',
       'nearest_mall_en', 'rooms_en', 'has_parking', 'procedure_area',
       'actual_worth', 'meter_sale_price', 'no_of_parties_role_1',
       'no_of_parties_role_2', 'no_of_parties_role_3'],
      dtype='object')

In [38]:
categorical_columns = [
    'trans_group_en',
    'reg_type_en',
    'area_name_en',
    'nearest_landmark_en',
    'nearest_metro_en',
    'nearest_mall_en',
    'building_name_en',
    'project_name_en',
    'master_project_en',
    'rooms_en',
    'has_parking'
]

summary_table = pd.DataFrame({
    'Data Type': df[categorical_columns].dtypes.astype(str),
    'Missing Values': df[categorical_columns].isna().sum(),
    'Unique Values': df[categorical_columns].nunique(dropna=True)
})

summary_table

                    Data Type  Missing Values  Unique Values
trans_group_en         object               0              3
reg_type_en            object               0              2
area_name_en           object               0            126
nearest_landmark_en    object           62637             13
nearest_metro_en       object           92471             48
nearest_mall_en        object           95152              5
building_name_en       object           27893           3945
project_name_en        object           24257           2384
master_project_en      object           27985            133
rooms_en               object            7174             12
has_parking             int64               0              2

# 6. Export

In [41]:
df.reset_index(drop=True, inplace=True)

In [43]:
df.to_csv('transactions_2025.csv', index=False)